### PR TITLE
Support Unicode filename/path

### PR DESCRIPTION
**Pull request by nguyenq**

### CODE REVIEW

**Comment by 4F2E4A2E** [comment]
Hey dear @nguyenq! Can you provide a unit test?
Thanks for the documentation in there: https://github.com/zippy1978/ghost4j/pull/64/commits/2c41c91b6cf23916a75664dacafe9274e988a710#diff-eeee69bca255b7121fab13fc6e8b78d9R334

**Comment by nguyenq** [comment]
Please check out the latest commit. Thanks.

**Comment by 4F2E4A2E** [comment]
That's great @nguyenq , thanks again.
@zippy1978 looks good to me, merging.

**Comment by 4F2E4A2E** [comment]
@zippy1978 can you take over the release?

**Pull request merged**
